#!/bin/sh

#
# Check if Homebrew is installed
#
which -s brew
if [[ $? != 0 ]] ; then
    # Install Homebrew
    # http://brew.sh/
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    brew update
fi

./brew_packets_base
./brew_packets_cask
./brew_packets_programming_languages
./brew_packets_programming_tools
./brew_packets_programming_utils
./brew_packets_text_editors
./brew_packets_browsers
./brew_packets_utilities

brew doctor