#!/bin/sh

#
# Check if Homebrew is installed
#

source packets

which -s brew
if [[ $? != 0 ]] ; then
    # Install Homebrew
    # http://brew.sh/
    echo "Installing homebrew. See http://brew.sh/ for help!"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	echo "homebrew is already installed. Updating instead."
    brew update
fi

echo "Enabling brew cask"
./brew_packets_cask

brew install $packets_base $packets_programming_languages $packets_programming_tools $packets_programming_utils
brew cask install $packets_text_editors $packets_browsers $packets_utilities

brew doctor