#!/bin/sh
brew update
brew cask install 1password thunderbird skype steam dropbox teamviewer caffeine gpgtools filezilla tunnelblick whatsapp keka moneymoney bettertouchtool veracrypt vlc spotify slack reaper gemini arq calibre transmission little-snitch mactex
