#!/bin/sh
packets_base="curl wget bash-completion git git-extras git-flow rclone sqlite youtube-dl encfs mobile-shell zsh zsh-completions"
packets_programming_languages="gcc gdb ghc erlang go python python3 ruby"
packets_programming_tools="cmake make"
packets_programming_utils="virtualbox hopper-disassembler dash docker"
packets_text_editors="sublime-text macvim atom qt-creator"
packets_browsers="google-chrome firefox"
packets_utilities="1password thunderbird skype steam amazon-drive dropbox teamviewer caffeine gpgtools filezilla tunnelblick whatsapp keka moneymoney bettertouchtool veracrypt vlc spotify slack reaper gemini arq calibre transmission little-snitch mactex"
packets_drivers="logitech-options"
